[rospy.client][INFO] 2020-09-02 04:06:12,904: init_node, name[/listener_2378_1599019572848], pid[2378]
[xmlrpc][INFO] 2020-09-02 04:06:12,905: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-02 04:06:12,906: Started XML-RPC server [http://192.168.137.54:35013/]
[rospy.init][INFO] 2020-09-02 04:06:12,907: ROS Slave URI: [http://192.168.137.54:35013/]
[rospy.impl.masterslave][INFO] 2020-09-02 04:06:12,907: _ready: http://192.168.137.54:35013/
[rospy.registration][INFO] 2020-09-02 04:06:12,909: Registering with master node http://192.168.137.54:11311
[xmlrpc][INFO] 2020-09-02 04:06:12,909: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-02 04:06:13,008: registered with master
[rospy.rosout][INFO] 2020-09-02 04:06:13,008: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-02 04:06:13,017: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-02 04:06:13,020: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-02 04:06:13,080: topic[/camera/rgb/image_raw] adding connection to [http://192.168.137.54:37013/], count 0
[rospy.msg][ERROR] 2020-09-02 04:06:13,124: cannot deserialize message: EXCEPTION Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 223, in deserialize_messages
    msg_queue.append(data.deserialize(q))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_Image.py", line 147, in deserialize
    codecs.lookup_error("rosmsg").msg_type = self._type
LookupError: unknown error handler name 'rosmsg'

[rospy.internal][ERROR] 2020-09-02 04:06:13,127: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 735, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 398, in read_messages
    deserialize_messages(b, msg_queue, self.recv_data_class, queue_size=self.queue_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 245, in deserialize_messages
    raise genpy.DeserializationError("cannot deserialize: %s"%str(e))
DeserializationError: cannot deserialize: unknown error handler name 'rosmsg'

[rospy.internal][WARNING] 2020-09-02 04:06:13,134: Unknown error initiating TCP/IP socket to 192.168.137.54:40247 (http://192.168.137.54:37013/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 378, in read_ros_handshake_header
    return decode_ros_handshake_header(bval)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 327, in decode_ros_handshake_header
    raise ROSHandshakeException("Invalid 0-length handshake header field")
ROSHandshakeException: Invalid 0-length handshake header field

[rospy.internal][INFO] 2020-09-02 04:06:13,135: topic[/camera/rgb/image_raw] removing connection to http://192.168.137.54:37013/
[rospy.internal][INFO] 2020-09-02 04:06:13,237: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-09-02 04:07:10,370: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-09-02 04:07:10,381: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-09-02 04:07:10,382: signal-2
[rospy.core][INFO] 2020-09-02 04:07:10,490: signal_shutdown [atexit]
