[rospy.client][INFO] 2020-09-02 04:48:55,339: init_node, name[/rostopic_6464_1599022135290], pid[6464]
[xmlrpc][INFO] 2020-09-02 04:48:55,340: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-02 04:48:55,341: Started XML-RPC server [http://192.168.137.54:43701/]
[rospy.init][INFO] 2020-09-02 04:48:55,341: ROS Slave URI: [http://192.168.137.54:43701/]
[rospy.impl.masterslave][INFO] 2020-09-02 04:48:55,342: _ready: http://192.168.137.54:43701/
[rospy.registration][INFO] 2020-09-02 04:48:55,343: Registering with master node http://192.168.137.54:11311
[xmlrpc][INFO] 2020-09-02 04:48:55,343: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-02 04:48:55,442: registered with master
[rospy.rosout][INFO] 2020-09-02 04:48:55,443: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-02 04:48:55,453: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-02 04:48:55,457: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-02 04:48:55,743: topic[/camera/rgb/image_raw/compressed] adding connection to [http://192.168.137.54:39131/], count 0
[rospy.msg][ERROR] 2020-09-02 04:48:55,777: cannot deserialize message: EXCEPTION Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 223, in deserialize_messages
    msg_queue.append(data.deserialize(q))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/sensor_msgs/msg/_CompressedImage.py", line 117, in deserialize
    codecs.lookup_error("rosmsg").msg_type = self._type
LookupError: unknown error handler name 'rosmsg'

[rospy.internal][ERROR] 2020-09-02 04:48:55,778: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 735, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 398, in read_messages
    deserialize_messages(b, msg_queue, self.recv_data_class, queue_size=self.queue_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 245, in deserialize_messages
    raise genpy.DeserializationError("cannot deserialize: %s"%str(e))
DeserializationError: cannot deserialize: unknown error handler name 'rosmsg'

[rospy.internal][WARNING] 2020-09-02 04:48:55,781: Unknown error initiating TCP/IP socket to 192.168.137.54:58705 (http://192.168.137.54:39131/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 378, in read_ros_handshake_header
    return decode_ros_handshake_header(bval)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 327, in decode_ros_handshake_header
    raise ROSHandshakeException("Invalid 0-length handshake header field")
ROSHandshakeException: Invalid 0-length handshake header field

[rospy.internal][INFO] 2020-09-02 04:48:55,782: topic[/camera/rgb/image_raw/compressed] removing connection to http://192.168.137.54:39131/
[rospy.internal][INFO] 2020-09-02 04:48:55,792: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2020-09-02 04:49:21,804: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-09-02 04:49:21,815: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-09-02 04:49:21,816: signal-2
[rospy.core][INFO] 2020-09-02 04:49:21,932: signal_shutdown [atexit]
